### ISSUE TITLE
请求失败请稍后重试

### ISSUE THREAD

**Issue by Vckers** [mengkong6/DailyHotUI#2]
大佬，你这个演示站[hot.sapi.run](https://hot.sapi.run/) 打开显示请求失败，请稍后重试。
原大佬[imsyy](https://github.com/imsyy)的也是加载不出来，可以抽空修复一下吗？

**Comment by mengkong6** [comment]
因为接口套了CDN导致的，目前已经关闭了CDN，多刷新几次就可以出现
