### ISSUE TITLE
新闻聚合站点 在手机上无法显示

### ISSUE THREAD

**Issue by lyzcodebool** [mengkong6/DailyHotUI#3]

**Comment by mengkong6** [comment]
这个问题之前解决过，自测安卓可以跳转，苹果没有手机不清楚

**Comment by lyzcodebool** [comment]
之前安卓是因为什么呢 我看看苹果我能不能调一下 现在我试了一下  安卓没问题 苹果不行  
顺便想问一下 原版的代码是不是只要部署了api  前端代码替换了那个全局api就可以了呢？
望解答 谢谢！
















在 2023-11-08 21:45:19，"mengkong6" ***@***.***> 写道：

这个问题之前解决过，自测安卓可以跳转，苹果没有手机不清楚
